// Shared constants — single source of truth for defaults and magic numbers

// ── Display name (change here to rename everywhere) ──
// NOTE: Also update manifest.json "name" field — it can't read JS constants.
const APP_NAME = 'Brainrot Blocker';
const APP_NAME_FULL = 'Brainrot Blocker';

const DEFAULTS = {
  workMinutes: 50,
  rewardMinutes: 10,
  rewardSites: [
    // Social Media
    'facebook.com',
    'instagram.com',
    'twitter.com',
    'x.com',
    'tiktok.com',
    'snapchat.com',
    'linkedin.com',
    'pinterest.com',
    'tumblr.com',
    'reddit.com',
    'discord.com',
    'telegram.org',
    'whatsapp.com',
    'messenger.com',
    // Video Platforms
    'youtube.com',
    'twitch.tv',
    'vimeo.com',
    'dailymotion.com',
    'netflix.com',
    'hulu.com',
    'disneyplus.com',
    'primevideo.com',
    'hbomax.com',
    'peacocktv.com',
    'paramountplus.com',
    'crunchyroll.com',
    // News
    'cnn.com',
    'bbc.com',
    'nytimes.com',
    'theguardian.com',
    'washingtonpost.com',
    'foxnews.com',
    'reuters.com',
    'apnews.com',
    'nbcnews.com',
    'bloomberg.com',
    'wsj.com',
    'usatoday.com',
    // Shopping
    'amazon.com',
    'ebay.com',
    'etsy.com',
    'walmart.com',
    'target.com',
    'bestbuy.com',
    'aliexpress.com',
    'wish.com',
    'shein.com',
    'zappos.com',
    'wayfair.com',
    'overstock.com',
    // Gaming
    'steampowered.com',
    'epicgames.com',
    'roblox.com',
    'minecraft.net',
    'ign.com',
    'gamespot.com',
    'polygon.com',
    'kotaku.com',
    'pcgamer.com',
    'ea.com',
    'ubisoft.com',
  ],
  productiveSites: [
    'docs.google.com',
    'notion.so',
    'github.com',
    // Music & Production
    'ableton.com',
    'image-line.com',
    'native-instruments.com',
    'izotope.com',
    'waves.com',
    'fabfilter.com',
    'arturia.com',
    'spotify.com',
    'soundcloud.com',
    'bandcamp.com',
    'beatport.com',
    'syntorial.com',
    'sonicacademy.com',
    'pointblankmusicschool.com',
    'producertech.com',
  ],
  allowedPaths: [],
  skipProductivityCheck: [],
  productiveMode: 'all-except-blocked',
  productiveApps: [],
  blockedApps: [],
  strictMode: 'off',
  penaltyEnabled: 'off',
  penaltyType: 'Charity',
  penaltyTarget: '',
  penaltyAmount: 5,
  paymentMethod: '',
  companionMode: 'off',
};

const CURATED_APPS = [
  // Commonly Used
  { name: 'PowerShell', process: 'powershell', category: 'Commonly Used' },
  { name: 'Visual Studio Code', process: 'Code', category: 'Commonly Used' },
  { name: 'Windows Terminal', process: 'WindowsTerminal', category: 'Commonly Used' },
  // Communication
  { name: 'Discord', process: 'Discord', category: 'Communication' },
  { name: 'Microsoft Teams', process: 'ms-teams', category: 'Communication' },
  { name: 'Slack', process: 'slack', category: 'Communication' },
  { name: 'Zoom', process: 'Zoom', category: 'Communication' },
  // Office
  { name: 'Adobe Acrobat', process: 'Acrobat', category: 'Office' },
  { name: 'Microsoft Excel', process: 'EXCEL', category: 'Office' },
  { name: 'Microsoft PowerPoint', process: 'POWERPNT', category: 'Office' },
  { name: 'Microsoft Word', process: 'WINWORD', category: 'Office' },
  // Productivity
  { name: 'ClickUp', process: 'ClickUp', category: 'Productivity' },
  { name: 'Notion', process: 'Notion', category: 'Productivity' },
  { name: 'Obsidian', process: 'Obsidian', category: 'Productivity' },
  { name: 'OneNote', process: 'ONENOTE', category: 'Productivity' },
  { name: 'Todoist', process: 'Todoist', category: 'Productivity' },
  // AI Assistants
  { name: 'ChatGPT Desktop', process: 'ChatGPT', category: 'AI Assistants' },
  { name: 'Claude Desktop', process: 'claude', category: 'AI Assistants' },
  { name: 'Cursor', process: 'Cursor', category: 'AI Assistants' },
  // Design
  { name: 'Adobe Illustrator', process: 'Illustrator', category: 'Design' },
  { name: 'Adobe Photoshop', process: 'Photoshop', category: 'Design' },
  { name: 'Blender', process: 'blender', category: 'Design' },
  { name: 'Figma', process: 'Figma', category: 'Design' },
  { name: 'Unity', process: 'Unity', category: 'Design' },
  // Music Production
  { name: 'Cubase', process: 'cubase', category: 'Music Production' },
  { name: 'FL Studio (64-bit)', process: 'FL64', category: 'Music Production' },
  { name: 'Kontakt', process: 'Kontakt', category: 'Music Production' },
  { name: 'Maschine 2', process: 'Maschine 2', category: 'Music Production' },
  { name: 'Pro Tools', process: 'Protools', category: 'Music Production' },
  { name: 'Reaper', process: 'reaper', category: 'Music Production' },
  { name: 'Reason', process: 'reason', category: 'Music Production' },
  { name: 'rekordbox', process: 'rekordbox', category: 'Music Production' },
  { name: 'Serato DJ Pro', process: 'Serato DJ Pro', category: 'Music Production' },
  { name: 'Splice', process: 'Splice', category: 'Music Production' },
  { name: 'Studio One', process: 'Studio One', category: 'Music Production' },
  { name: 'VirtualDJ', process: 'virtualdj_pro', category: 'Music Production' },
  // Development — IDEs & Editors
  { name: 'Android Studio', process: 'studio64', category: 'Development' },
  { name: 'JetBrains IDEs', process: 'idea64', category: 'Development' },
  { name: 'Notepad++', process: 'notepad++', category: 'Development' },
  { name: 'PyCharm', process: 'pycharm64', category: 'Development' },
  { name: 'Sublime Text', process: 'sublime_text', category: 'Development' },
  { name: 'Vim/Neovim', process: 'nvim', category: 'Development' },
  { name: 'Visual Studio', process: 'devenv', category: 'Development' },
  { name: 'WebStorm', process: 'webstorm64', category: 'Development' },
  // Development — Terminals & Tools
  { name: 'Command Prompt', process: 'cmd', category: 'Development' },
  { name: 'Docker Desktop', process: 'Docker Desktop', category: 'Development' },
  { name: 'Git Bash', process: 'mintty', category: 'Development' },
  { name: 'Insomnia', process: 'Insomnia', category: 'Development' },
  { name: 'Postman', process: 'Postman', category: 'Development' },
  // Development — Database
  { name: 'Azure Data Studio', process: 'azuredatastudio', category: 'Development' },
  { name: 'DBeaver', process: 'dbeaver', category: 'Development' },
  { name: 'MySQL Workbench', process: 'MySQLWorkbench', category: 'Development' },
  { name: 'pgAdmin', process: 'pgAdmin4', category: 'Development' },
  { name: 'SQL Workbench', process: 'SQLWorkbench', category: 'Development' },
  { name: 'SSMS', process: 'Ssms', category: 'Development' },
  // Deployment & Hosting
  { name: 'FileZilla', process: 'filezilla', category: 'Deployment & Hosting' },
  { name: 'PuTTY', process: 'putty', category: 'Deployment & Hosting' },
  { name: 'WinSCP', process: 'WinSCP', category: 'Deployment & Hosting' },
  // Virtualization
  { name: 'Hyper-V Manager', process: 'virtmgmt', category: 'Virtualization' },
  { name: 'VirtualBox', process: 'VirtualBoxVM', category: 'Virtualization' },
  { name: 'VMware Player', process: 'vmplayer', category: 'Virtualization' },
  { name: 'VMware Workstation', process: 'vmware', category: 'Virtualization' },
];

const PRESET_BLOCKED_SITES = [
  // Social Media
  { name: 'Facebook', domain: 'facebook.com', category: 'Social Media', checked: true },
  { name: 'Instagram', domain: 'instagram.com', category: 'Social Media', checked: true },
  { name: 'Twitter / X', domains: ['twitter.com', 'x.com'], category: 'Social Media', checked: true },
  { name: 'TikTok', domain: 'tiktok.com', category: 'Social Media', checked: true },
  { name: 'Snapchat', domain: 'snapchat.com', category: 'Social Media', checked: true },
  { name: 'Reddit', domain: 'reddit.com', category: 'Social Media', checked: true },
  { name: 'Discord', domain: 'discord.com', category: 'Social Media', checked: false },
  { name: 'LinkedIn', domain: 'linkedin.com', category: 'Social Media', checked: false },
  { name: 'Pinterest', domain: 'pinterest.com', category: 'Social Media', checked: false },
  { name: 'Tumblr', domain: 'tumblr.com', category: 'Social Media', checked: false },
  { name: 'Telegram', domain: 'telegram.org', category: 'Social Media', checked: false },
  { name: 'WhatsApp', domain: 'whatsapp.com', category: 'Social Media', checked: false },
  { name: 'Messenger', domain: 'messenger.com', category: 'Social Media', checked: false },
  // Video & Streaming
  { name: 'YouTube', domain: 'youtube.com', category: 'Video & Streaming', checked: true },
  { name: 'Twitch', domain: 'twitch.tv', category: 'Video & Streaming', checked: true },
  { name: 'Netflix', domain: 'netflix.com', category: 'Video & Streaming', checked: true },
  { name: 'Hulu', domain: 'hulu.com', category: 'Video & Streaming', checked: false },
  { name: 'Disney+', domain: 'disneyplus.com', category: 'Video & Streaming', checked: false },
  { name: 'Prime Video', domain: 'primevideo.com', category: 'Video & Streaming', checked: false },
  { name: 'HBO Max', domain: 'hbomax.com', category: 'Video & Streaming', checked: false },
  { name: 'Peacock', domain: 'peacocktv.com', category: 'Video & Streaming', checked: false },
  { name: 'Paramount+', domain: 'paramountplus.com', category: 'Video & Streaming', checked: false },
  { name: 'Crunchyroll', domain: 'crunchyroll.com', category: 'Video & Streaming', checked: false },
  { name: 'Vimeo', domain: 'vimeo.com', category: 'Video & Streaming', checked: false },
  { name: 'Dailymotion', domain: 'dailymotion.com', category: 'Video & Streaming', checked: false },
  // News
  { name: 'CNN', domain: 'cnn.com', category: 'News', checked: false },
  { name: 'BBC', domain: 'bbc.com', category: 'News', checked: false },
  { name: 'NY Times', domain: 'nytimes.com', category: 'News', checked: false },
  { name: 'The Guardian', domain: 'theguardian.com', category: 'News', checked: false },
  { name: 'Washington Post', domain: 'washingtonpost.com', category: 'News', checked: false },
  { name: 'Fox News', domain: 'foxnews.com', category: 'News', checked: false },
  { name: 'Reuters', domain: 'reuters.com', category: 'News', checked: false },
  { name: 'AP News', domain: 'apnews.com', category: 'News', checked: false },
  { name: 'NBC News', domain: 'nbcnews.com', category: 'News', checked: false },
  { name: 'Bloomberg', domain: 'bloomberg.com', category: 'News', checked: false },
  { name: 'WSJ', domain: 'wsj.com', category: 'News', checked: false },
  { name: 'USA Today', domain: 'usatoday.com', category: 'News', checked: false },
  // Shopping — general
  { name: 'Amazon', domain: 'amazon.com', category: 'Shopping', checked: false },
  { name: 'eBay', domain: 'ebay.com', category: 'Shopping', checked: false },
  { name: 'Walmart', domain: 'walmart.com', category: 'Shopping', checked: false },
  { name: 'Target', domain: 'target.com', category: 'Shopping', checked: false },
  { name: 'Costco', domain: 'costco.com', category: 'Shopping', checked: false },
  { name: 'Etsy', domain: 'etsy.com', category: 'Shopping', checked: false },
  { name: 'Wish', domain: 'wish.com', category: 'Shopping', checked: false },
  { name: 'Temu', domain: 'temu.com', category: 'Shopping', checked: false },
  { name: 'AliExpress', domain: 'aliexpress.com', category: 'Shopping', checked: false },
  // Shopping — electronics & home
  { name: 'Best Buy', domain: 'bestbuy.com', category: 'Shopping', checked: false },
  { name: 'Newegg', domain: 'newegg.com', category: 'Shopping', checked: false },
  { name: 'Wayfair', domain: 'wayfair.com', category: 'Shopping', checked: false },
  { name: 'Overstock', domain: 'overstock.com', category: 'Shopping', checked: false },
  { name: 'Home Depot', domain: 'homedepot.com', category: 'Shopping', checked: false },
  { name: 'Chewy', domain: 'chewy.com', category: 'Shopping', checked: false },
  // Shopping — fashion
  { name: 'SHEIN', domain: 'shein.com', category: 'Shopping', checked: false },
  { name: 'ASOS', domain: 'asos.com', category: 'Shopping', checked: false },
  { name: 'Zara', domain: 'zara.com', category: 'Shopping', checked: false },
  { name: 'H&M', domain: 'hm.com', category: 'Shopping', checked: false },
  { name: 'Nike', domain: 'nike.com', category: 'Shopping', checked: false },
  { name: 'Adidas', domain: 'adidas.com', category: 'Shopping', checked: false },
  { name: 'Nordstrom', domain: 'nordstrom.com', category: 'Shopping', checked: false },
  { name: "Macy's", domain: 'macys.com', category: 'Shopping', checked: false },
  { name: 'Zappos', domain: 'zappos.com', category: 'Shopping', checked: false },
  // Gaming — platforms
  { name: 'Steam', domain: 'steampowered.com', category: 'Gaming', checked: false },
  { name: 'Epic Games', domain: 'epicgames.com', category: 'Gaming', checked: false },
  { name: 'Roblox', domain: 'roblox.com', category: 'Gaming', checked: false },
  { name: 'Minecraft', domain: 'minecraft.net', category: 'Gaming', checked: false },
  // Gaming — games
  { name: 'League of Legends', domain: 'leagueoflegends.com', category: 'Gaming', checked: false },
  { name: 'Valorant', domain: 'playvalorant.com', category: 'Gaming', checked: false },
  { name: 'Fortnite', domain: 'fortnite.com', category: 'Gaming', checked: false },
  { name: 'Apex Legends', domain: 'apexlegends.com', category: 'Gaming', checked: false },
  { name: 'World of Warcraft', domain: 'worldofwarcraft.com', category: 'Gaming', checked: false },
  { name: 'Overwatch 2', domain: 'playoverwatch.com', category: 'Gaming', checked: false },
  // Gaming — news
  { name: 'IGN', domain: 'ign.com', category: 'Gaming', checked: false },
  { name: 'GameSpot', domain: 'gamespot.com', category: 'Gaming', checked: false },
  { name: 'Polygon', domain: 'polygon.com', category: 'Gaming', checked: false },
  { name: 'Kotaku', domain: 'kotaku.com', category: 'Gaming', checked: false },
  { name: 'PC Gamer', domain: 'pcgamer.com', category: 'Gaming', checked: false },
  // Gambling — sports betting
  { name: 'DraftKings', domain: 'draftkings.com', category: 'Gambling', checked: false },
  { name: 'FanDuel', domain: 'fanduel.com', category: 'Gambling', checked: false },
  { name: 'BetMGM', domain: 'betmgm.com', category: 'Gambling', checked: false },
  { name: 'Caesars Sportsbook', domain: 'caesarssportsbook.com', category: 'Gambling', checked: false },
  { name: 'bet365', domain: 'bet365.com', category: 'Gambling', checked: false },
  { name: 'Betway', domain: 'betway.com', category: 'Gambling', checked: false },
  { name: 'William Hill', domain: 'williamhill.com', category: 'Gambling', checked: false },
  { name: 'BetRivers', domain: 'betrivers.com', category: 'Gambling', checked: false },
  { name: 'PointsBet', domain: 'pointsbet.com', category: 'Gambling', checked: false },
  { name: 'Hard Rock Bet', domain: 'hardrock.bet', category: 'Gambling', checked: false },
  { name: 'Unibet', domain: 'unibet.com', category: 'Gambling', checked: false },
  { name: 'bwin', domain: 'bwin.com', category: 'Gambling', checked: false },
  { name: 'Bovada', domain: 'bovada.lv', category: 'Gambling', checked: false },
  { name: 'MyBookie', domain: 'mybookie.ag', category: 'Gambling', checked: false },
  { name: 'BetOnline', domain: 'betonline.ag', category: 'Gambling', checked: false },
  { name: 'SportsBetting.ag', domain: 'sportsbetting.ag', category: 'Gambling', checked: false },
  { name: 'PrizePicks', domain: 'prizepicks.com', category: 'Gambling', checked: false },
  { name: 'Fliff', domain: 'getfliff.com', category: 'Gambling', checked: false },
  { name: 'Barstool Sportsbook', domain: 'barstoolsports.com', category: 'Gambling', checked: false },
  { name: 'Ladbrokes', domain: 'ladbrokes.com', category: 'Gambling', checked: false },
  { name: 'Paddy Power', domain: 'paddypower.com', category: 'Gambling', checked: false },
  // Gambling — online casinos & poker
  { name: '888 Casino', domain: '888casino.com', category: 'Gambling', checked: false },
  { name: 'PokerStars', domain: 'pokerstars.com', category: 'Gambling', checked: false },
  { name: 'GGPoker', domain: 'ggpoker.com', category: 'Gambling', checked: false },
  { name: 'partypoker', domain: 'partypoker.com', category: 'Gambling', checked: false },
  { name: 'WSOP', domain: 'wsop.com', category: 'Gambling', checked: false },
  // Adult Sites
  { name: 'OnlyFans', domain: 'onlyfans.com', category: 'Adult Sites', checked: false },
  {
    name: 'Adult Websites',
    domains: [
      'pornhub.com', 'xvideos.com', 'xnxx.com', 'redtube.com', 'youporn.com',
      'xhamster.com', 'tube8.com', 'spankbang.com', 'beeg.com', 'eporner.com',
      'vporn.com', 'txxx.com', 'tnaflix.com', 'fuq.com', 'hclips.com',
      'drtuber.com', 'nuvid.com', 'pornone.com', 'empflix.com', 'brazzers.com',
      'realitykings.com', 'bangbros.com', 'naughtyamerica.com', 'anyporn.com',
      'hotmovs.com', 'cliphunter.com', 'ixxx.com', 'pornmd.com', 'alphaporno.com',
      'porntrex.com', 'sxyprn.com', 'porntube.com', 'fapster.xxx', 'gotporn.com',
      'faphouse.com',
    ],
    category: 'Adult Sites',
    checked: false,
  },
];

const PRESET_PRODUCTIVE_SITES = [
  // Productivity
  { name: 'Google Docs', domain: 'docs.google.com', category: 'Productivity', checked: true },
  { name: 'Google Drive', domain: 'drive.google.com', category: 'Productivity', checked: true },
  { name: 'Google Sheets', domain: 'sheets.google.com', category: 'Productivity', checked: true },
  { name: 'Notion', domain: 'notion.so', category: 'Productivity', checked: true },
  { name: 'Trello', domain: 'trello.com', category: 'Productivity', checked: false },
  { name: 'Asana', domain: 'asana.com', category: 'Productivity', checked: false },
  { name: 'ClickUp', domain: 'app.clickup.com', category: 'Productivity', checked: false },
  { name: 'Linear', domain: 'linear.app', category: 'Productivity', checked: false },
  // Development
  { name: 'GitHub', domain: 'github.com', category: 'Development', checked: true },
  { name: 'Stack Overflow', domain: 'stackoverflow.com', category: 'Development', checked: true },
  { name: 'MDN Web Docs', domain: 'developer.mozilla.org', category: 'Development', checked: false },
  { name: 'GitLab', domain: 'gitlab.com', category: 'Development', checked: false },
  { name: 'CodePen', domain: 'codepen.io', category: 'Development', checked: false },
  // AI Tools
  { name: 'Claude', domain: 'claude.ai', category: 'AI Tools', checked: false },
  { name: 'ChatGPT', domain: 'chat.openai.com', category: 'AI Tools', checked: false },
  { name: 'Gemini', domain: 'gemini.google.com', category: 'AI Tools', checked: false },
  { name: 'Perplexity', domain: 'perplexity.ai', category: 'AI Tools', checked: false },
  // Music Production
  { name: 'Splice', domain: 'splice.com', category: 'Music Production', checked: false },
  { name: 'Bandcamp', domain: 'bandcamp.com', category: 'Music Production', checked: false },
  { name: 'SoundCloud', domain: 'soundcloud.com', category: 'Music Production', checked: false },
  { name: 'Beatport', domain: 'beatport.com', category: 'Music Production', checked: false },
  { name: 'Sonic Academy', domain: 'sonicacademy.com', category: 'Music Production', checked: false },
  { name: 'Point Blank School', domain: 'pointblankmusicschool.com', category: 'Music Production', checked: false },
  { name: 'ProducerTech', domain: 'producertech.com', category: 'Music Production', checked: false },
];

const PRODUCTIVITY_CHECK_MINUTES = 10; // minutes before "Are you really working?" popup

const NATIVE_HOST_NAME = 'com.brainrotblocker.native';

const ALARM_PERIOD_MINUTES = 0.25;
const ALLOW_RULE_ID_OFFSET = 1000;
const NUCLEAR_RULE_ID_OFFSET = 2000;

// Preset sites for Nuclear Block (permanent, always-on blocking with staged cooldowns)
const PRESET_NUCLEAR_SITES = [
  { name: 'OnlyFans', domain: 'onlyfans.com' },
  {
    name: 'Adult Websites',
    domains: [
      'pornhub.com', 'xvideos.com', 'xnxx.com', 'redtube.com', 'youporn.com',
      'xhamster.com', 'tube8.com', 'spankbang.com', 'beeg.com', 'eporner.com',
      'vporn.com', 'txxx.com', 'tnaflix.com', 'fuq.com', 'hclips.com',
      'drtuber.com', 'nuvid.com', 'pornone.com', 'empflix.com', 'brazzers.com',
      'realitykings.com', 'bangbros.com', 'naughtyamerica.com', 'anyporn.com',
      'hotmovs.com', 'cliphunter.com', 'ixxx.com', 'pornmd.com', 'alphaporno.com',
      'porntrex.com', 'sxyprn.com', 'porntube.com', 'fapster.xxx', 'gotporn.com',
      'faphouse.com',
    ],
  },
  {
    name: 'Gambling Sites',
    domains: [
      'draftkings.com', 'fanduel.com', 'betmgm.com', 'caesarssportsbook.com',
      'bet365.com', 'betway.com', 'williamhill.com', 'betrivers.com',
      'pointsbet.com', 'hardrock.bet', 'unibet.com', 'bwin.com',
      'bovada.lv', 'mybookie.ag', 'betonline.ag', 'sportsbetting.ag',
      'prizepicks.com', 'getfliff.com', 'barstoolsports.com', 'ladbrokes.com',
      'paddypower.com', '888casino.com', 'pokerstars.com', 'ggpoker.com',
      'partypoker.com', 'wsop.com',
    ],
  },
  { name: 'Steam', domain: 'steampowered.com' },
  { name: 'Epic Games', domain: 'epicgames.com' },
  { name: 'League of Legends', domain: 'leagueoflegends.com' },
  { name: 'World of Warcraft', domain: 'worldofwarcraft.com' },
  { name: 'Valorant', domain: 'playvalorant.com' },
];
